# Generated by Django 4.2.7 on 2025-03-13 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(blank=True, null=True)),
                ('attendance_percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='SubjectGrade',
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='performance_app.course'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='performance_app.student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together={('student', 'course')},
        ),
    ]
