# Generated by Django 4.2.7 on 2025-03-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0002_studentgrade_remove_student_courses_course_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='performance_app.student'),
        ),
    ]
