# Generated by Django 4.2.7 on 2025-03-25 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance_app', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedPredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm', models.CharField(default='GradientBoosting', max_length=50)),
                ('train_test_split', models.FloatField(default=0.2)),
                ('r_squared', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='prediction_models/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_for_models', to='performance_app.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_grade', models.FloatField()),
                ('actual_grade', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='performance_app.enhancedpredictionmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='ModelTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_in_training', models.BooleanField(default=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='performance_app.enhancedpredictionmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_app.student')),
            ],
            options={
                'unique_together': {('model', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ModelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_app.course')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='performance_app.enhancedpredictionmodel')),
            ],
            options={
                'unique_together': {('model', 'course')},
            },
        ),
    ]
