# Generated by Django 4.2.7 on 2025-03-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0003_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
