# Generated by Django 4.2.7 on 2025-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0004_enhancedpredictionmodel_modelprediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['level', 'name'], name='performance_level_407393_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgrade',
            index=models.Index(fields=['student', 'course'], name='performance_student_7e7ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgrade',
            index=models.Index(fields=['course', 'grade'], name='performance_course__668ada_idx'),
        ),
    ]
