# Generated by Django 4.2.7 on 2025-03-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0005_alter_student_level_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprediction',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
