# Generated by Django 4.2.7 on 2025-04-01 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0006_modelprediction_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTestPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_grade', models.FloatField()),
                ('predicted_grade', models.FloatField()),
                ('absolute_error', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_predictions', to='performance_app.enhancedpredictionmodel')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_app.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
