# Generated by Django 4.2.7 on 2025-04-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_app', '0007_modeltestprediction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelprediction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='modelprediction',
            unique_together={('model', 'student')},
        ),
    ]
